# Generated by Django 5.2.7 on 2025-12-31 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('grupo_muscular', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('series', models.IntegerField(default=3)),
                ('repeticoes', models.IntegerField(default=12)),
                ('carga', models.IntegerField(default=0, help_text='Carga em Kg')),
            ],
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('objetivo', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('idade', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoTreino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
            ],
            options={
                'verbose_name': 'Treino do Aluno',
                'verbose_name_plural': 'Treinos dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='MedidasAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objetivo', models.CharField(max_length=100)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=4)),
                ('data_registro', models.DateField(auto_now_add=True)),
                ('peito', models.DecimalField(decimal_places=2, max_digits=5)),
                ('braco_esquerdo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('braco_direito', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quadril', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perna_esquerda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perna_direita', models.DecimalField(decimal_places=2, max_digits=5)),
                ('panturrilha_esquerda', models.DecimalField(decimal_places=2, max_digits=5)),
                ('panturrilha_direita', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='home.aluno')),
            ],
            options={
                'verbose_name': 'Medidas do Aluno',
                'verbose_name_plural': 'Medidas dos Alunos',
                'ordering': ['-data_registro'],
            },
        ),
        migrations.CreateModel(
            name='Treinador',
            fields=[
                ('cref', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('formacao', models.TextField()),
                ('idade', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='treinador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='home.treinador'),
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(max_length=50)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('alunos', models.ManyToManyField(related_name='treinos', through='home.AlunoTreino', through_fields=('treino', 'aluno'), to='home.aluno')),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos_criados', to='home.treinador')),
            ],
        ),
        migrations.AddField(
            model_name='alunotreino',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.treino'),
        ),
        migrations.CreateModel(
            name='TreinoExercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('carga', models.IntegerField(default=0, help_text='Carga em Kg')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.exercicio')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.treino')),
            ],
            options={
                'verbose_name': 'Exercício no Treino',
                'verbose_name_plural': 'Exercícios nos Treinos',
                'unique_together': {('treino', 'exercicio')},
            },
        ),
        migrations.AddField(
            model_name='treino',
            name='exercicios',
            field=models.ManyToManyField(related_name='treinos', through='home.TreinoExercicio', through_fields=('treino', 'exercicio'), to='home.exercicio'),
        ),
        migrations.AlterUniqueTogether(
            name='alunotreino',
            unique_together={('aluno', 'treino')},
        ),
    ]
