# Generated by Django 6.0.1 on 2026-01-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinador',
            name='cpf',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
