# Generated by Django 5.2.7 on 2026-01-23 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='treinador',
        ),
        migrations.CreateModel(
            name='ConexaoAlunoTreinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('ENCERRADA', 'Encerrada')], default='PENDENTE', max_length=10)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='home.aluno')),
                ('treinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexoes', to='home.treinador')),
            ],
            options={
                'unique_together': {('aluno', 'treinador')},
            },
        ),
    ]
