# Generated by Django 6.0.1 on 2026-01-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_treinador_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinador',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
