# Generated by Django 5.2.7 on 2026-01-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_aluno_treinador_conexaoalunotreinador'),
        ('home', '0003_alter_treinador_cpf'),
    ]

    operations = [
    ]
