# Generated by Django 6.0.1 on 2026-01-23 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_treinador_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaTreinoAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('DOM', 'Domingo'), ('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('SAB', 'Sábado')], max_length=3)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias_treino', to='home.aluno')),
            ],
            options={
                'verbose_name': 'Dia de treino do aluno',
                'verbose_name_plural': 'Dias de treino do aluno',
                'unique_together': {('aluno', 'dia')},
            },
        ),
    ]
