# Generated by Django 6.0.1 on 2026-01-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_diatreinoaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='dias_disponiveis',
            field=models.CharField(default='', help_text='Dias da semana separados por vírgula. Ex: Segunda,Quarta,Sexta', max_length=100),
            preserve_default=False,
        ),
    ]
