# Generated by Django 5.2.7 on 2026-01-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20260123_1405'),
        ('home', '0005_aluno_dias_disponiveis'),
    ]

    operations = [
    ]
