# Generated by Django 6.0.1 on 2026-01-25 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20260123_1405'),
        ('home', '0005_aluno_dias_disponiveis'),
    ]

    operations = [
    ]
