# Generated by Django 5.2.7 on 2026-01-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20260125_1756'),
        ('home', '0006_merge_20260125_1912'),
    ]

    operations = [
    ]
