# Generated by Django 6.0.1 on 2026-01-27 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aluno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='repeticoes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='series',
            field=models.IntegerField(default=0),
        ),
    ]
