# Generated by Django 5.2.7 on 2026-01-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_aluno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='meta_peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
