# Generated by Django 5.2.7 on 2026-01-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_aluno_antebraco_direito_aluno_antebraco_esquerdo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedidasAluno',
        ),
    ]
