# Generated by Django 5.2.7 on 2026-01-27 08:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_delete_medidasaluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercicioConcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateTimeField(default=django.utils.timezone.now)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.aluno')),
                ('treino_exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.treinoexercicio')),
            ],
            options={
                'unique_together': {('aluno', 'treino_exercicio')},
            },
        ),
    ]
