# Generated by Django 6.0.1 on 2026-01-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_exercicio_repeticoes_alter_exercicio_series'),
        ('home', '0012_exercicioconcluido'),
    ]

    operations = [
    ]
