# Generated by Django 6.0.1 on 2026-01-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_merge_20260127_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='treinador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_treinadores/'),
        ),
        migrations.AddField(
            model_name='treinador',
            name='instagram',
            field=models.CharField(blank=True, help_text='Apenas o @', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='treinador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
